from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = true
disable_bump_commit = false
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = true
pre_bump_hooks = [
  "cargo set-version {{version}}",  # bump version in Cargo.toml
  "git add :/Cargo.lock",           # stage version bump in Cargo.lock
]
post_bump_hooks = [
  "git push origin",
  "git push origin {{version}}",
]
