name: Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  draft:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get tag
        id: get_tag
        run: |
          tag="$(git describe --tags --abbrev=0)" ; [ -n "$tag" ] || exit 1
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
      - name: Create draft release
        run: |
          tag="${{ steps.get_tag.outputs.tag }}"
          if ! gh release view "$tag" >/dev/null 2>&1; then
            gh release create "$tag" --draft --title "$tag"
          fi

  release:
    needs: draft
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary_name: "pyload-tui-linux"
          - os: macos-latest
            binary_name: "pyload-tui-mac"
          - os: windows-latest
            binary_name: "pyload-tui-windows.exe"
            ext: ".exe"
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}
      TARGET: ''
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Set target triple
        run: |
          target="$(rustc --version --verbose | awk '/host:/ { print $2 }')" ; [ -n "$target" ] || exit 1
          echo "TARGET=$target" >> "$GITHUB_ENV"
      - name: Build
        run: cargo build --target "${{ env.TARGET }}" --release
      - name: Locate and rename binary
        run: |
          binary_path="target/${{ env.TARGET }}/release/pyload-tui${{ matrix.ext }}"

          [ -f "$binary_path" ] || exit 1

          mv "$binary_path" "${{ matrix.binary_name }}"

          echo "BINARY_PATH=${{ matrix.binary_name }}" >> "$GITHUB_ENV"
      - name: Upload to release
        run: gh release upload "${{ needs.draft.outputs.tag }}" "$BINARY_PATH"

  publish:
    needs: [draft, release]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Publish release
        run: gh release edit "${{ needs.draft.outputs.tag }}" --draft=false

  cleanup:
    needs: publish
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Remove previous releases
        run: |
          gh release list --limit 1000 --json tagName --jq '.[1:][] | .tagName' |
          xargs -r -I{} gh release delete '{}' --yes
